openapi: 3.0.0
info:
  title: "EzCopnnect REST API"
  description: "An API about people and courses"
  version: "0.0.2"

servers:
  - url: "/api"

components:
  schemas:
    SignUpNewUser:
      type: "object"
      required:
        - name
        - email
        - year
        - degree
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        year:
          type: integer
          maximum: 6
          minimum: 1
        degree:
          type: string
        programme:
          type: string
  parameters:
    user_id:
      in: path
      name: user_id
      required: true
      schema:
        type: string
        minLength: 36
        maxLength: 36
        format: uuid
      description: "User ID"
  securitySchemes:
    # Keeping it as JWT to faciliate debugging
    # Get the token manually from frontend and input it to authorise...
    # Swagger does not see mto support 
    # Also help in debugging as we can use a custom dev only jwt to skip
    # Azure B2C login, which is hard to do in CI/CD in the future...
    jwt:
      type: http
      description: |
        This actually relies on Azure AD B2C in the frontend for login
        Kept as JWT to enable manual input of the access token in Swagger UI
        for testing purposes. Swagger does not seem to work with Auth Code Flow 
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: "ezConnect.auth.login.decode_token"

        
paths: 
  /user/create-user:
    put: 
      operationId: "ezConnect.auth.signup.create_user"
      tags:
        - "Sign Up"
      summary: |
        Create account for user after logging in with Azure AD B2C.
        User ID comes from Azure B2C, will be used as primary key.
        UserId will come from token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpNewUser"
            example:
              name: "John Doe"
              email: "EXXXXXXX@u.nus.edu"
              year: 2
              degree: "Double major in Social Work and Psychology"
              programme: "College of Alice and Peter Tan"
              azure_ad_oid: 12345678-1234-1234-1234-1234abvdefgh
      security:
        - jwt: []
      responses:
        "200":
          description: User ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: integer
        "409":
          description: "Invalid request: user already exist in database"
  /auth/login/who-am-i:
    get:
      operationId: "ezConnect.auth.login.who_am_i"
      tags:
        - "Auth"
      summary: "Returns the user ID of the authenticated user"
      security:
        - jwt: []
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  azure_ad_oid:
                    type: string
                  user_id:
                    type: string
                  name:
                    type: string
        '401':
          description: Unauthorized


