"""empty message

Revision ID: 087c180a629d
Revises: 19dfd3388254
Create Date: 2023-05-28 09:44:14.483746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087c180a629d'
down_revision = '19dfd3388254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_up_request', schema=None) as batch_op:
        batch_op.drop_constraint('sign_up_request_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_up_request', schema=None) as batch_op:
        batch_op.create_unique_constraint('sign_up_request_email_key', ['email'])

    # ### end Alembic commands ###
