"""empty message

Revision ID: 5d9bb93bb669
Revises: 0f60b0932ff1
Create Date: 2023-07-07 11:48:49.528257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9bb93bb669'
down_revision = '0f60b0932ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_study_plan',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('published_study_plan_id', sa.UUID(), nullable=False),
    sa.Column('date_viewed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['published_study_plan_id'], ['published_study_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.azure_ad_oid'], )
    )
    with op.batch_alter_table('favorited_study_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_favourited', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint('unique_user_favourited_study_plan', ['user_id', 'published_study_plan_id'])

    with op.batch_alter_table('liked_study_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_liked', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint('unique_user_liked_study_plan', ['user_id', 'published_study_plan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liked_study_plan', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_liked_study_plan', type_='unique')
        batch_op.drop_column('date_liked')

    with op.batch_alter_table('favorited_study_plan', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_favourited_study_plan', type_='unique')
        batch_op.drop_column('date_favourited')

    op.drop_table('viewed_study_plan')
    # ### end Alembic commands ###
