"""empty message

Revision ID: 75c6bd359a83
Revises: 087c180a629d
Create Date: 2023-06-17 08:56:44.448823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c6bd359a83'
down_revision = '087c180a629d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('course_code', sa.String(length=8), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=True),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('is_offered_in_sem1', sa.Boolean(), nullable=False),
    sa.Column('is_offered_in_sem2', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_table('prerequisites',
    sa.Column('prerequisite_id', sa.String(length=8), nullable=True),
    sa.Column('course_id', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['course.course_code'], )
    )
    op.create_table('study_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('num_of_likes', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_plan_semester',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_number')
    )
    op.create_table('semester_course',
    sa.Column('study_plan_semester_id', sa.UUID(), nullable=True),
    sa.Column('course_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['study_plan_semester_id'], ['study_plan_semester.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semester_course')
    op.drop_table('study_plan_semester')
    op.drop_table('study_plan')
    op.drop_table('prerequisites')
    op.drop_table('course')
    op.drop_table('academic_plan')
    # ### end Alembic commands ###
