"""empty message

Revision ID: 9d4370465dbd
Revises: 5d9bb93bb669
Create Date: 2023-07-09 15:30:08.834787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4370465dbd'
down_revision = '5d9bb93bb669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('published_study_plan_id', sa.UUID(), nullable=False),
    sa.Column('first_degree_id', sa.UUID(), nullable=False),
    sa.Column('second_degree_id', sa.UUID(), nullable=True),
    sa.Column('second_major', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['first_degree_id'], ['degree.id'], ),
    sa.ForeignKeyConstraint(['published_study_plan_id'], ['published_study_plan.id'], ),
    sa.ForeignKeyConstraint(['second_degree_id'], ['degree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minor_academic_plan',
    sa.Column('minor_id', sa.UUID(), nullable=True),
    sa.Column('academic_plan_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['academic_plan_id'], ['academic_plan.id'], ),
    sa.ForeignKeyConstraint(['minor_id'], ['programme.id'], )
    )
    op.create_table('special_programmes_academic_plan',
    sa.Column('special_programme_id', sa.UUID(), nullable=True),
    sa.Column('academic_plan_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['academic_plan_id'], ['academic_plan.id'], ),
    sa.ForeignKeyConstraint(['special_programme_id'], ['programme.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_programmes_academic_plan')
    op.drop_table('minor_academic_plan')
    op.drop_table('academic_plan')
    # ### end Alembic commands ###
