"""empty message

Revision ID: a545d5020e5d
Revises: 087c180a629d
Create Date: 2023-06-18 06:38:25.935342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a545d5020e5d'
down_revision = '087c180a629d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_code', sa.String(length=8), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=True),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('is_offered_in_sem1', sa.Boolean(), nullable=False),
    sa.Column('is_offered_in_sem2', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_table('degree',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programme',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_user',
    sa.Column('course_code', sa.String(length=8), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('degree_user',
    sa.Column('degree_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['degree.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('prerequisites',
    sa.Column('prerequisite_code', sa.String(length=8), nullable=True),
    sa.Column('course_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['prerequisite_code'], ['course.course_code'], )
    )
    op.create_table('programme_user',
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('study_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('num_of_likes', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_plan_semester',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_number')
    )
    op.create_table('semester_course',
    sa.Column('study_plan_semester_id', sa.UUID(), nullable=True),
    sa.Column('course_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], ),
    sa.ForeignKeyConstraint(['study_plan_semester_id'], ['study_plan_semester.id'], )
    )
    op.drop_table('sign_up_request')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azure_ad_oid', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint('azure_ad_oid_unique', ['azure_ad_oid'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('course')
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('azure_ad_oid_unique', type_='unique')
        batch_op.drop_column('azure_ad_oid')

    op.create_table('sign_up_request',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('creation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sign_up_request_pkey')
    )
    op.drop_table('semester_course')
    op.drop_table('study_plan_semester')
    op.drop_table('study_plan')
    op.drop_table('programme_user')
    op.drop_table('prerequisites')
    op.drop_table('degree_user')
    op.drop_table('course_user')
    op.drop_table('programme')
    op.drop_table('degree')
    op.drop_table('course')
    # ### end Alembic commands ###
