"""empty message

Revision ID: e534acc545c3
Revises: f0c3451c1967
Create Date: 2023-07-15 06:11:50.142071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e534acc545c3'
down_revision = 'f0c3451c1967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prerequisites', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prerequisites', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    # ### end Alembic commands ###
