"""empty message

Revision ID: f0c3451c1967
Revises: 9d4370465dbd
Create Date: 2023-07-12 15:01:09.579756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c3451c1967'
down_revision = '9d4370465dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prerequisites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite_str', sa.Text(), nullable=True))
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=12),
               existing_nullable=True)
        batch_op.drop_constraint('prerequisites_prerequisite_code_fkey', type_='foreignkey')
        batch_op.drop_column('prerequisite_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prerequisites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('prerequisites_prerequisite_code_fkey', 'course', ['prerequisite_code'], ['course_code'])
        batch_op.alter_column('course_code',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('prerequisite_str')

    # ### end Alembic commands ###
