import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'MS logo Sign in' }).click();
  // Need to let it wait, probably being defeated by anti bot mechanism
  // Find a way to manually wait for us to input?
  await page.goto('https://login.microsoftonline.com/5ba5ef5e-3109-4e77-85bd-cfeb0d347e82/oauth2/v2.0/authorize?client_id=31e1fcdd-460b-4509-af8b-64fdbd68440a&redirect_uri=https%3a%2f%2fezconnecttesting.b2clogin.com%2fezconnecttesting.onmicrosoft.com%2foauth2%2fauthresp&response_type=code&scope=openid+profile+email&response_mode=form_post&nonce=Cdyqm89mFz1%2b%2bFgEMiML%2bQ%3d%3d&ui_locales=en-US&state=StateProperties%3deyJTSUQiOiJ4LW1zLWNwaW0tcmM6MWUyYzhhZWYtZTE4NS00MWQwLTgzOWUtY2FkM2I2N2NiYmMxIiwiVElEIjoiNjk2NDJiNmMtYjRkZC00NTUzLThhNDMtZmIyYzZmZGUwNDE4IiwiVE9JRCI6ImUwMzA1ZTNmLTJiOGEtNDQxNS1hMWU4LTBmYjQ3Y2U4NzBhNyJ9');
  await page.getByPlaceholder('Email, phone, or Skype').click();
  await page.getByPlaceholder('Email, phone, or Skype').fill('E0958769@u.nus.edu');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByPlaceholder('Password').fill(`${process.env.NUS_PASSWORD}`);
  await page.getByPlaceholder('Password').click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'Mentoring' }).click();
  await page.frameLocator('#webpack-dev-server-client-overlay').getByLabel('Dismiss').click();
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'MS logo Sign in' }).click();
  await page.goto('http://localhost:3000/homepage#state=eyJpZCI6IjMxZTcwMzU1LTNkYmMtNDJiYi1hNGUwLTc5MjdlOGViYmJjYSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3d%7c%2f&client_info=eyJ1aWQiOiI3ZGM0ZDRmYS1kZDM5LTRlMmItOWY5Ni1kOGFhZDQwM2NkNjMtYjJjXzFfZXpjb25uZWN0ZGV2X3N1c2kiLCJ1dGlkIjoiZTAzMDVlM2YtMmI4YS00NDE1LWExZTgtMGZiNDdjZTg3MGE3In0&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..YS3JHA1Lvvg285wd.i8lWnjiag_2ulBCLrpF05e127sUbM5WJx5_-Dy4uRSpo8-PBeYAKaiCwZBhfvCSqkPotj0KhLwb121GK3eS8tKS1AA6HQfbYdn_B3efv9lLDL8Vduz8mHnq0jQT01WCNXrJwr_gQBd2gnjzC7qY5shtvCkSY0aq8VlMUWf1npsAOPbdQCGGOL8nPMTrJytyThQ_exHGreA8TKA6BqOvFaqNu3bUBrmRBparBD7zUSDm1ZSWsNcAOUaeNBW5u0FA0Z06AgQgliukMTfe_FhPyHXAoWXFIBd7LjYnvXUQDTJvzCLZL2v0ldWbTLwzvbCf5ExGIFBfnKSGGwMmjV2xY-Hg5xrJGfxak3TwlI9YfSJNdLqlcrPnThSleUNk48BC-bDVdu3MtBPMd8kxY_aRi4yRzeZ6Q0nvTCLwrw9PKxbKq_5762AdSz2SsKjWsc3xRhnwFbBNE_0lOuHmTCip9MUllMm4UtnyovLbhHOfsen8vbB4UptFJMvSqStvHnCgkB1Xjr2xgIElSqp9jZuko1Q7wadMrA8x1y7xxvtCA2Ssykdb7NiuYJ-k35ki5vblCTeN3Blv7jVkMlkQh6W6XhB2krgg_F2fVQ_uzNq8fxVovXzzmsKacR_SZuk0WnSSMNmsK4jTDQFMqmNiqtQSEn_Sd0i507Qope04ietBhMy96M1BZjfuMeyzn8n8E2fHOyzyS80zOCkALNmSpqp52x0HB0N5QxNBI6qUiBwdVVRecdZWdwQtsJEDphorRXbO8p8sPT80iiGbA4IaZMplsZpmrJvGDcaPPJjYNMp69ynDcpi5vIf3ZEudRQSkbRrrgV9v-2E0dhxvl59uiKC7RLJTAZ3c4C89S7DAnbP92R9xFOUwlf3WCE05c9ePLq6P4.YN6h8ESl7CSfQVTTJLXoiA');
  await page.goto('http://localhost:3000/homepage#');
  await page.goto('http://localhost:3000/homepage');
  await page.goto('http://localhost:3000/user/create-account');
  await page.locator('.css-1xc3v61-indicatorContainer').first().click();
  await page.locator('#react-select-3-input').fill('C');
  await page.locator('#react-select-3-input').press('CapsLock');
  await page.locator('#react-select-3-input').fill('Comp');
  await page.getByText('Computer Science', { exact: true }).click();
  await page.locator('.css-1fdsijx-ValueContainer > .css-qbdosj-Input').click();
  await page.getByText('University Town College Programme', { exact: true }).click();
  await page.locator('#react-select-5-input').fill('minor in int');
  await page.getByText('Minor in Interactive Media Development', { exact: true }).dblclick();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Create Posting' }).click();
  await page.locator('.css-qbdosj-Input').click();
  await page.locator('#root div').filter({ hasText: 'Create a mentor postingThis lets people know your interest in mentoring a partic' }).click();
  await page.locator('.css-qbdosj-Input').click();
  await page.locator('#react-select-7-input').fill('cs1101s');
  await page.getByText('CS1101S Programming Methodology', { exact: true }).click();
  await page.getByPlaceholder('Post Ttitle').click();
  await page.getByPlaceholder('Post Ttitle').fill('H');
  await page.getByPlaceholder('Post Ttitle').press('CapsLock');
  await page.getByPlaceholder('Post Ttitle').fill('Hello');
  await page.getByPlaceholder('Post Ttitle').press('Tab');
  await page.getByPlaceholder('Tell us more about yourself!').press('CapsLock');
  await page.getByPlaceholder('Tell us more about yourself!').fill('H');
  await page.getByPlaceholder('Tell us more about yourself!').press('CapsLock');
  await page.getByPlaceholder('Tell us more about yourself!').fill('Heiii');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Study Plan' }).click();
  await page.getByRole('button', { name: 'Create one now' }).click();
  await page.locator('.css-qbdosj-Input').first().click();
  await page.getByPlaceholder('NUSMods Timetable Share Link').click();
  await page.getByPlaceholder('NUSMods Timetable Share Link').click();
  await page.getByPlaceholder('NUSMods Timetable Share Link').fill('https://nusmods.com/timetable/sem-2/share?CS1231S=TUT:09,LEC:1&CS2030S=LAB:10H,REC:06,LEC:1&MA1521=LEC:1,TUT:6&NTW2034=SEM:1&ST1131=TUT:6,LEC:1');
  await page.locator('.flex > .css-b62m3t-container > .css-13cymwt-control > .css-1fdsijx-ValueContainer > .css-qbdosj-Input').click();
  await page.locator('#react-select-13-option-0').click();
  await page.getByRole('button', { name: 'Import' }).click();
  await page.getByPlaceholder('NUSMods Timetable Share Link').click({
    modifiers: ['Control']
  });
  await page.getByPlaceholder('NUSMods Timetable Share Link').fill('https://nusmods.com/timetable/sem-2/share?CS1231S=TUT:09,LEC:https://nusmods.com/timetable/sem-2/share?CS1231S=TUT:09,LEC:1&CS2030S=LAB:10H,REC:06,LEC:1&MA1521=LEC:1,TUT:6&NTW2034=SEM:1&ST1131=TUT:6,LEC:1\')) print(parse_nus_mods(\'https://nusmods.com/timetable/sem-1/share?CS2030S=LEC:1,LAB:12B&CS2100=REC:1,LEC:1,TUT:09,LAB:25&IS1108=TUT:20,LEC:2&MA1301=LEC:21&CS2030S=LAB:10H,REC:06,LEC:1&MA1521=LEC:1,TUT:6&NTW2034=SEM:1&ST1131=TUT:6,LEC:1');
  await page.getByPlaceholder('NUSMods Timetable Share Link').press('Control+a');
  await page.getByPlaceholder('NUSMods Timetable Share Link').fill('https://nusmods.com/timetable/sem-2/share?CS1231S=TUT:09,LEC:1&CS2030S=LAB:10H,REC:06,LEC:1&MA1521=LEC:1,TUT:6&NTW2034=SEM:1&ST1131=TUT:6,LEC:1\')) print(parse_nus_mods(\'https://nusmods.com/timetable/sem-1/share?CS2030S=LEC:1,LAB:12B&CS2100=REC:1,LEC:1,TUT:09,LAB:25&IS1108=TUT:20,LEC:2&MA1301=LEC:2');
  await page.locator('#importCourses svg').click();
  await page.locator('#react-select-13-option-1').click();
  await page.getByRole('button', { name: 'Import' }).click();
  await page.locator('[id="headlessui-menu-button-\\:r5\\:"]').click();
  await page.getByRole('menuitem', { name: 'Validate Prerequisites' }).click();
  await page.getByRole('button', { name: 'Validate pre-requisites' }).click();
  await page.getByText('Validate pre-requisitesNot valid study planCS2030S did not have its pre-requisit').click();
  await page.locator('.fixed > .relative > .absolute').click();
  await page.getByRole('button', { name: 'CS2030S' }).first().click();
  await page.getByRole('button', { name: 'CS2030S' }).first().click();
  await page.getByRole('button', { name: 'CS2030S' }).first().click();
  await page.getByRole('button', { name: 'CS2030S' }).first().click();
  await page.locator('div').filter({ hasText: /^Y2S1Total units: 0$/ }).locator('div').nth(3).click();
  await page.getByRole('button', { name: 'CS2030S' }).nth(2).click({
    modifiers: ['Shift']
  });
  await page.getByRole('button', { name: 'CS2030S' }).nth(2).click({
    modifiers: ['Shift']
  });
  await page.getByRole('button', { name: 'CS2030S' }).nth(2).click({
    modifiers: ['Control']
  });
  await page.getByRole('button', { name: 'CS2030S' }).nth(2).click();
  await page.getByRole('button', { name: 'CS2030S' }).nth(2).click();
  await page.locator('[id="headlessui-menu-button-\\:rd\\:"]').click();
  await page.getByRole('menuitem', { name: 'Clear semester' }).click();
  await page.frameLocator('#webpack-dev-server-client-overlay').getByLabel('Dismiss').click();
  await page.getByPlaceholder('NUSMods Timetable Share Link').click();
  await page.getByPlaceholder('NUSMods Timetable Share Link').press('Control+a');
  await page.getByPlaceholder('NUSMods Timetable Share Link').fill('https://nusmods.com/timetable/sem-2/share?CS1231S=TUT:09,LEC:1&CS2030S=LAB:10H,REC:06,LEC:1&MA1521=LEC:1,TUT:6&NTW2034=SEM:1&ST1131=TUT:6,LEC:1');
  await page.getByRole('button', { name: 'Import' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.css-qbdosj-Input').first().click();
  await page.locator('#react-select-11-input').fill('cs1101s');
  await page.locator('#react-select-11-input').press('Enter');
  await page.locator('[id="headlessui-menu-button-\\:r5\\:"]').click();
  await page.getByRole('menuitem', { name: 'Validate Prerequisites' }).click();
  await page.getByRole('button', { name: 'Validate pre-requisites' }).click();
  await page.getByText('Validate pre-requisitesNot valid study planCS2030S did not have its pre-requisit').click();
  await page.locator('.fixed > .relative > .absolute').click();
  await page.getByRole('button', { name: 'CS2030S' }).nth(1).click();
  await page.getByRole('button', { name: 'CS2030S' }).nth(1).click();
  await page.getByRole('button', { name: 'CS2030S' }).nth(1).click();
  await page.locator('[id="headlessui-menu-button-\\:rh\\:"]').click();
  await page.getByRole('menuitem', { name: 'Clear semester' }).click();
  await page.locator('[id="headlessui-menu-button-\\:r5\\:"]').click();
  await page.getByRole('menuitem', { name: 'Validate Prerequisites' }).click();
  await page.getByRole('button', { name: 'Validate pre-requisites' }).click();
  await page.locator('.absolute > path').click();
  await page.locator('[id="headlessui-menu-button-\\:r5\\:"]').click();
  await page.getByRole('menuitem', { name: 'Publish' }).click();
  await page.getByLabel('Title *').click();
  await page.getByLabel('Title *').fill('');
  await page.getByLabel('Title *').press('CapsLock');
  await page.getByLabel('Title *').fill('CS STUDY PLAN1');
  await page.getByLabel('Title *').press('Shift+ArrowLeft');
  await page.getByLabel('Title *').press('Tab');
  await page.getByLabel('Description').fill('YEAR 1');
  await page.getByLabel('Description').press('CapsLock');
  await page.getByLabel('Description').fill('YEAR 1 ');
  await page.locator('.css-qbdosj-Input').first().click();
  await page.locator('#react-select-15-input').press('CapsLock');
  await page.locator('#react-select-15-input').fill('C');
  await page.locator('#react-select-15-input').press('CapsLock');
  await page.locator('#react-select-15-input').fill('COmp');
  await page.locator('#react-select-15-input').press('Enter');
  await page.locator('#react-select-15-input').press('Tab');
  await page.locator('#react-select-17-input').press('Tab');
  await page.getByPlaceholder('Second Major (Optional)').press('Tab');
  await page.locator('#react-select-19-input').press('CapsLock');
  await page.locator('#react-select-19-input').fill('I');
  await page.locator('#react-select-19-input').press('CapsLock');
  await page.locator('#react-select-19-input').fill('Inter');
  await page.locator('#react-select-19-input').press('ArrowDown');
  await page.locator('#react-select-19-input').press('Tab');
  await page.locator('#react-select-19-input').press('Tab');
  await page.locator('#react-select-21-input').press('CapsLock');
  await page.locator('#react-select-21-input').fill('U');
  await page.locator('#react-select-21-input').press('CapsLock');
  await page.locator('#react-select-21-input').fill('Un');
  await page.locator('#react-select-21-input').press('Enter');
  await page.locator('#react-select-21-input').press('Tab');
  await page.getByRole('button', { name: 'Publish' }).press('Enter');
  await page.locator('.fixed > .relative > .absolute').click();
  await page.getByRole('link', { name: 'Study Plan' }).click();
  await page.getByText('CS STUDY PLAN1').click();
  await page.locator('div').filter({ hasText: /^0$/ }).getByRole('img').click();
  await page.locator('#postButtons').getByRole('img').click();
  await page.getByRole('button', { name: 'Make a copy' }).click();
  await page.locator('div').filter({ hasText: /^Saved$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Saved$/ }).getByRole('textbox').fill('CS STUDY PLAN2');
  await page.getByRole('link', { name: 'Study Plan' }).click();
  await page.getByRole('link', { name: 'Mentoring' }).click();
  await page.getByRole('tab', { name: 'Matches as mentee' }).click();
  await page.getByRole('tab', { name: 'Requests for mentor' }).click();
});