# This workflow will deploy
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy ezConnect docker compose to Azure VM

on:
  push:
    branches: [ "release**", "*ms*"]
  pull_request:
    branches: [ "release**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Run ansible playbook
      run: |
        sudo apt install -y sshpass
        pip install docker
        ansible-playbook infra/playbooks/deploy.yaml -i infra/.inventory \
          --extra-vars "ansible_user=${{ secrets.ANSIBLE_USER }} \
            ansible_password=${{ secrets.ANSIBLE_PASSWORD }} \
            git_username=${{ secrets.GIT_USERNAME }} \
            git_pat=${{ secrets.GIT_PAT }} \
            MAILERCFW_API_KEY=${{ secrets.MAILERCFW_API_KEY }} \
            CLOUDFLARED_SECRET=${{ secrets.CLOUDFLARED_SECRET }}"



