# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and check ezConnect

on:
  # push:

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install -r backend/requirements.txt
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        cd frontend; npm ci; cd ..
    - name: Lint with ruff
      continue-on-error: true
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff --format=github --target-version=py311 --exit-zero . 
    - name: Prepare test database
      run: |
        ./backend/tests/setUpTestDB.sh
    - name: Test with pytest
      run: |
        export MAILERCFW_API_KEY='${{ secrets.MAILERCFW_API_KEY }}'
        cd backend/
        python -m pytest -vv
        cd ..
    - name: Lint JS files
      continue-on-error: true
      run: |
        cd frontend
        npm install
        npx eslint src
    - name: Install Playwright Browsers
      run: cd frontend; npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
